project:
  name: Ozon Code Platform Template API
  debug: true
  environment: development

grpc:
  host: 127.0.0.1
  port: 6002
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

gateway:
  host: 127.0.0.1
  port: 6000
  allowedCorsOrigins:
    - "http://localhost:7001"
    - "http://0.0.0.0:7001"
    - "http://127.0.0.1:7001"

swagger:
  host: 127.0.0.1
  port: 6001
  filepath: "swagger/api/product-service/product-service.swagger.json"

categoryService:
  basePath: 127.0.0.1:7002