// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package category_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryServiceClient interface {
	CategoryMethodV1(ctx context.Context, in *CategoryMethodV1Request, opts ...grpc.CallOption) (*CategoryMethodV1Response, error)
	GetCategoryByIdV1(ctx context.Context, in *GetCategoryByIdV1Request, opts ...grpc.CallOption) (*GetCategoryByIdV1Response, error)
}

type categoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryServiceClient(cc grpc.ClientConnInterface) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) CategoryMethodV1(ctx context.Context, in *CategoryMethodV1Request, opts ...grpc.CallOption) (*CategoryMethodV1Response, error) {
	out := new(CategoryMethodV1Response)
	err := c.cc.Invoke(ctx, "/kosenkovd.category_service.category_service.v1.CategoryService/CategoryMethodV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) GetCategoryByIdV1(ctx context.Context, in *GetCategoryByIdV1Request, opts ...grpc.CallOption) (*GetCategoryByIdV1Response, error) {
	out := new(GetCategoryByIdV1Response)
	err := c.cc.Invoke(ctx, "/kosenkovd.category_service.category_service.v1.CategoryService/GetCategoryByIdV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
// All implementations must embed UnimplementedCategoryServiceServer
// for forward compatibility
type CategoryServiceServer interface {
	CategoryMethodV1(context.Context, *CategoryMethodV1Request) (*CategoryMethodV1Response, error)
	GetCategoryByIdV1(context.Context, *GetCategoryByIdV1Request) (*GetCategoryByIdV1Response, error)
	mustEmbedUnimplementedCategoryServiceServer()
}

// UnimplementedCategoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (UnimplementedCategoryServiceServer) CategoryMethodV1(context.Context, *CategoryMethodV1Request) (*CategoryMethodV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryMethodV1 not implemented")
}
func (UnimplementedCategoryServiceServer) GetCategoryByIdV1(context.Context, *GetCategoryByIdV1Request) (*GetCategoryByIdV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryByIdV1 not implemented")
}
func (UnimplementedCategoryServiceServer) mustEmbedUnimplementedCategoryServiceServer() {}

// UnsafeCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryServiceServer will
// result in compilation errors.
type UnsafeCategoryServiceServer interface {
	mustEmbedUnimplementedCategoryServiceServer()
}

func RegisterCategoryServiceServer(s grpc.ServiceRegistrar, srv CategoryServiceServer) {
	s.RegisterService(&CategoryService_ServiceDesc, srv)
}

func _CategoryService_CategoryMethodV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryMethodV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).CategoryMethodV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kosenkovd.category_service.category_service.v1.CategoryService/CategoryMethodV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).CategoryMethodV1(ctx, req.(*CategoryMethodV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_GetCategoryByIdV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryByIdV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).GetCategoryByIdV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kosenkovd.category_service.category_service.v1.CategoryService/GetCategoryByIdV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).GetCategoryByIdV1(ctx, req.(*GetCategoryByIdV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryService_ServiceDesc is the grpc.ServiceDesc for CategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kosenkovd.category_service.category_service.v1.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CategoryMethodV1",
			Handler:    _CategoryService_CategoryMethodV1_Handler,
		},
		{
			MethodName: "GetCategoryByIdV1",
			Handler:    _CategoryService_GetCategoryByIdV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/product-service/product-service.proto",
}
